#+title:  Is Julia Ready for Deep Learning
#+date:   <2020-11-10>
#+KEYWORDS: Julialang, Julia, deep learning, DL

I heard about Swift and Julia for deep learning during
[[https://www.youtube.com/watch?v=3TqN_M1L4ts][fast.ai's course]]. Then
I spent quite some time to try figuring out whether any of these
languages is a better choice for deep learning than Python. However,
soon I realized that Chris Lattner left Google and Swift for Tensorflow
project is slowing down and even [[https://twimlai.com/whats-next-for-fast-ai-w-jeremy-howard/][Jeremy
Howard is less passionate about it]]. Then the only choice left for now
is Julia AFAIK. The Question is whether Julia is ready for deep
learning.

* Memory Management
  :PROPERTIES:
  :CUSTOM_ID: memory-management
  :END:
I noticed this issue when Chris Lattner pointed during a
[[https://twimlai.com/the-great-ml-language-un-debate/][debate]]. In
short, Julia uses the Garbage Collector. It may cause memory not being
released in time. This is especially problematic for GPU since its
memory is much smaller than CPU memory. The good news is there is some
[[https://juliagpu.gitlab.io/CUDA.jl/usage/memory/][workaround]], but it
would be better if Julia has some deterministic memory management. There
is an
[[https://discourse.julialang.org/t/proposal-for-deterministic-memory-management/39305][ongoing
discussion about this]].

* Speed
  :PROPERTIES:
  :CUSTOM_ID: speed
  :END:
I guess most people come to Julia for speed. However, to get the optimal
speed, it is not that straight forward. One problem is to
[[https://www.youtube.com/watch?v=o8qTJGcPWkE][avoid allocation]].
Another problem is type inference. Julia is a dynamic typing language;
however, to get the best speed, you are encouraged to have type stability. Note that type annotation does not help if the compiler can figure out a stable type. In that case, annotating it to a narrower type only makes your function less reusable. IMO, dynamic typing is sometimes contradicting with this type stable idea. Therefore, Julia is in this awkward position that support dynamic typing, but when it causes type instability, it is not encouraged. I think static typing can make things much more straightforward. This leads to the next point I would like to mention.

* Ahead of Time (AOT) Compilation vs. Just In Time (JIT) Compilation vs. Interpreter
  :PROPERTIES:
  :CUSTOM_ID: ahead-of-time-aot-compilation-vs.-just-in-time-jit-compilation-vs.-interpreter
  :END:
Usually, static typing languages are AOT compiled while
dynamic language runs on an interpreter, and sometimes with a
JIT compiler. Because you need to know the type to deeply optimize the
code, static typing languages can directly be optimized AOT, while
dynamic typing languages can only to optimized at runtime when the
type is known with a JIT. Julia is somewhere in between. It is
[[https://www.youtube.com/watch?v=XWIZ_dCO6X8][just ahead of time
(JAOT)]] compiled. Julia does type inference as early as it can. But for a
dynamic type language, inevitably, the type cannot be inferred before runtime.
The pro is that you have a deeply optimized dynamic
typing language. The con is this JAOT takes a long time, and this is the
well known time to first plot issue. This issue is not a big deal if you
use Julia for deep learning. However, dynamic typing is something built
in the design of the language, while you enjoy the ease of use, you also
have to bear with the awkwardness it brings: 1) long JAOT compilation
time; 2) hard to build into libraries and executables. Luckily, both of
these two are being actively worked on ([[https://github.com/JuliaLang/PackageCompiler.jl][PackageCompiler.jl]], [[https://github.com/tshort/StaticCompiler.jl][StaticCompiler.jl]]) but awkwardly IMO.

* Community
  :PROPERTIES:
  :CUSTOM_ID: community
  :END:
Julia has a large scientific computing community. For deep learning,
there is also a community working on the
[[https://github.com/FluxML/ML-Coordination-Tracker][machine learning
ecosystem]].

* Solve Two Language Problem
  :PROPERTIES:
  :CUSTOM_ID: solve-two-language-problem
  :END:
I think this is a pretty unique point about Julia. People are proud of
using Julia from high-level all the way to low-level programming. The
fact that Julia can be used to do
[[https://www.youtube.com/watch?v=525t9-nsn5Y][CUDA programming]] just
blew my mind. Keep in mind that when you get into the advanced
metaprogramming in Julia, it feels quite different compared to the part
of Julia you normally use but it is technically still Julia language.

* Deep Learning Library and Auto Differentiation (AD)
  :PROPERTIES:
  :CUSTOM_ID: deep-learning-library-and-auto-differentiation-ad
  :END:
I guess a lot of people care about this the most. The reason I put it at
the very end is that it is not very mature yet. The most promising deep
learning library is called
[[https://github.com/FluxML/Flux.jl][Flux.jl]] and the AD it uses is
called [[https://github.com/FluxML/Zygote.jl][Zygote.jl]]. They are
still undergoing some changes. As far as I know, there may be a
[[https://youtu.be/mQnSRfseu0c][new AD]] coming out to replace Zygote.
Unlike Pytorch, where AD only works on Pytorch's Tensor class, Zygote is
a source to source AD that does not need to introduce another Tensor
class, it just works on the existing data structure. This can be a huge
advantage for developers. In Pytorch ecosystem, to be differentiable,
developers need to re-write their libraries using Pytorch's Tensor. For
example, [[https://github.com/kornia/kornia][Kornia]] is a re-write of
OpenCV using Pytorch. This will not happen to Julia package developer
since the AD will just work.

To summary up, IMHO, this is a very good time for early adopters and
people who want to make contributions. However, if you just want to get
things done, or you want the current best (fast and fully functional)
solution, Julia is not ready yet.

#+INCLUDE: ../utterance.org
