* 冥想是什么

** 两种思想
- 人有两种思想，一种是有意识可以控制的，偏逻辑的思考，比如你做题目，主动回忆啊，等等。很多人只意识到自己有这种思想。而其实人还有第二种不受控制的思想。他们感觉上就是自发的，不知道从哪蹦出来的念头。比如你准备睡觉的时候，本来打算什么都不想要睡了，但是乱七八糟的白天的烦心事儿或是开心事儿一件件往脑袋里面蹦。有的蹦出来一下就过去了，有的你还不由自主的动用第一种逻辑思想跟着一起想，结果就是睡不着。再比如，本来是要坐下来专心看书或者学习的，结果就是跟刚说的一样，一堆想法蹦出来，不知不觉溜号了。以一种我们叫它有意识的思想，第二种我们叫它自发无意识的思想。

- 第二种无意识思想被很多人忽视，愈演愈烈越来越无法控制，后果是有的人很难集中注意力；有的时候还会焦虑，心烦，比如潜意识里一直想着自己这个没做，那个要做，但是都没来得及做，最后就焦虑的。

** 坐在路边看车来车往
- 冥想就像是让第一种有意识的思想坐在路边，而无意识的思想就像是路上一辆辆的车，然后让有意识的思想去观察无意识思想。
- 最开始，可能你会被自己居然又这么多乱七八糟的想法所震惊。
- 接下来就是尝试不要被这些杂乱的想法代跑。比如刚才说的溜号，就相当于坐上了那辆车跟着跑了。有的人也会不希望某种不愉快的想法出现，所以强行阻止的情况。这就好比道路上去拦车。如果冥想时发现这种情况，应该让第一种意识立即回到路边坐着。
- 渐渐地，你会觉得路上的车越来越少，越来越平静。

** 蓝天和云
这是另一个比喻。就是把这些第二种杂乱想法比作云，有的是白云，有的是乌云。没有云的蓝天就是人们冥想最终追求的状态，虽然一开始肯定有很多云，渐渐的蓝天就浮现出来了。这个比喻强调的是虽然你最开始看不到蓝天，因为云太多，但是蓝天还是在的，放心。

** 驯野马
这是另一个比喻。意思是冥想不要操之过急，企图一下达到最终状态。就是要像训马一样，渐渐的收紧缰绳，慢慢驯服自己的思想。

** 遇到好的和坏的感觉怎么办
脑海里浮现的比一定只有想法，有的时候想法还会引起情绪的变化。遇到让你愉快的感觉时，尝试想象你把它分给你爱的人。遇到痛苦的感觉（比如坐着哪不舒服了）时，想象自己时在为别人承担痛苦。这样做的好处是会让不好的情绪更容易过去，而让好的情绪更持久。

** 应对负面感受
负面感受，可能是过去悲伤经历，或者是身体疾病造成的慢性疼痛。冥想时，可以观察这些负面感受的具体位置。比如悲伤，那么悲伤具体会让你哪里觉得不一样呢？作者的感受是，特没有特别具体的位置，而是像滤镜一样，让你是所有事物的看法都蒙上了颜色。最后，作者想表达的是这些负面情绪，或者疼痛，远远没有你想象的那么严重。很多都是你脑子潜意识认为有不适，然后自己越这么意识，越不舒服。换句话说是臆想出来的。冥想让你真正了解这些负面感受有多严重，具体在哪里，很可能没你想的严重。

* 如何冥想
** Take10：最常规的
*** Getting ready: 准备
找个地方坐，手机静音，减少干扰，设一个10分钟的提醒。
*** Checking-in: 冷静：五分钟
- 5次深呼吸
- 注意身体的受力点，跟椅子接触的地方
- 扫描全身，感受一下哪里舒服，哪里不适
- 感受自己目前的情绪
*** Focusing the mind：集中注意力
- 注意呼吸的起伏，节奏
- 数呼吸，吸，呼，吸……1,2,3,...
- 数到10重新回到1.
  如果你放心自己数的超过10，说明你溜号了。
- 重复数，一共5到10次
*** Finishing-off: 结束
- 放松注意力，随便瞎想20秒
- 重新注意身体的受力点。
- 睁眼。
** 睡前冥想
这个冥想有助睡眠，不过即使没有睡着，也可以让你发现你睡前脑子都在想些什么。
*** 睡前准备：
洗漱，甚至准备好第二天早起需要的东西。目的是，尽量减少牵挂，省的躺下一直想这个没做那个没做。
*** 冷静:
- 注意身体的受力点，跟床接触的地方
- 注意呼吸的起伏，节奏
*** 快速回顾这一天
- 不要想细节，不要被白天的事儿代跑了
- 更像是第三人称，简单的过一遍
*** 关闭全身
- 从脚趾，逐一关闭。
*** 从1000开始倒数



#+INCLUDE: ../utterance.org
